-- ============================================================
-- FastTicket ID 생성 테이블 초기화
-- IDS 테이블에 각 테이블별 NEXT_ID 시퀀스 등록
-- ============================================================

-- IDS 테이블이 없는 경우 생성 (MariaDB)
CREATE TABLE IF NOT EXISTS IDS (
    TABLE_NAME VARCHAR(16) NOT NULL,
    NEXT_ID    DECIMAL(30) NOT NULL,
    PRIMARY KEY (TABLE_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ID 생성 시퀀스';

-- 기존 FastTicket ID 레코드 삭제 (재실행 대비)
DELETE FROM IDS WHERE TABLE_NAME IN ('MEMBER', 'VENUE', 'SEAT', 'PROGRAM', 'TICKET_PRICE', 'SCHEDULE', 'BOOKING', 'BOOKING_DETAIL');

-- 각 테이블별 ID 시퀀스 초기값 등록
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('MEMBER', 1);
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('VENUE', 4);
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('SEAT', 11);
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('PROGRAM', 4);
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('TICKET_PRICE', 10);
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('SCHEDULE', 7);
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('BOOKING', 1);
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('BOOKING_DETAIL', 1);
